In [1]:
!pip install googlemaps
!pip install folium
!pip install haversine

Collecting googlemaps
  Downloading googlemaps-4.5.3.tar.gz (32 kB)
Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.7/dist-packages (from googlemaps) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (1.24.3)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py) ... done
  Created wheel for googlemaps: filename=googlemaps-4.5.3-py3-none-any.whl size=38481 sha256=57c48382e18a1ab6a983b30159d9fe1479df82f9272ba6f9dff74ba8e37b7388
  Stored in directory: /root/.cache/pip/wheels/fa/1a/1c/cc0b8a1652a3f06aea586b0e4714a81bafed830513969baf92
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.5.3
Requirement already satisfied: folium in /usr/local/lib/python3.7/dist-packages (0.8.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from folium) (2.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from folium) (2.23.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from folium) (1.15.0)
Requirement already satisfied: branca>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from folium) (0.4.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from folium) (1.19.5)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->folium) (2.0.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->folium) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->folium) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->folium) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->folium) (2.10)
Collecting haversine
  Downloading haversine-2.5.1-py2.py3-none-any.whl (6.1 kB)
Installing collected packages: haversine
Successfully installed haversine-2.5.1

In [1]:
import googlemaps
import folium
from haversine import haversine
from sklearn import preprocessing, cluster
from sklearn.metrics.pairwise import haversine_distances

from sklearn.cluster import DBSCAN
from geopy.distance import great_circle
from shapely.geometry import MultiPoint

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action="ignore") #경고 표시 제거는 일시적으로만 하자... 중요한 내용일수도

import matplotlib.font_manager as fm #한글 안깨지게
# font_name=fm.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
# plt.rc("font", family=font_name)

import matplotlib as mpl # - 표시 정상적으로 되도록
mpl.rcParams["axes.unicode_minus"]=False

import urllib.request as req
from urllib.request import urlopen
from urllib.error import HTTPError, URLError
import urllib.parse
from bs4 import BeautifulSoup
import requests

#from selenium import webdriver
import time

In [4]:
#할일 --> 중복포함 좌표리스트에서 cluster에 소속되지 않은 음식점을 가장 가까운 cluster로 배정

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [15]:
clusters = pd.read_csv("/content/drive/MyDrive/에이콘/0117 등원작업물/data/cluster 중간지점 좌표모음(470m).csv", sep=",")
places = pd.read_csv("/content/drive/MyDrive/에이콘/0117 등원작업물/data/중복포함 좌표리스트_소속 cluster(소속없는 음식점 입력필요).csv", sep=",")

In [42]:
type(places["경도"][0])

numpy.float64

In [47]:
idx = places[places["Cluster"]=="[]"].index
idx

Int64Index([  17,   18,   35,   40,   41,   42,   73,   82,   83,   84,
            ...
            4540, 4545, 4557, 4563, 4575, 4582, 4589, 4606, 4633, 4643],
           dtype='int64', length=633)

In [17]:
clusters.columns=["위도", "경도"]

In [ ]:
clusters

In [45]:
type(clusters["위도"][0])
type(clusters["경도"][0])

numpy.float64

In [52]:
for i in idx:
    print(i)
    distance = []
    location = (places["위도"][i], places["경도"][i])
    for j in range(len(clusters)):
        d=haversine(location, (clusters["위도"][j], clusters["경도"][j]))
        distance.append(d)
    min_distance_point=distance.index(min(distance))
    places["Cluster"][i] = [min_distance_point]

17
18
35
40
41
42
73
82
83
84
85
86
87
92
99
117
118
164
165
166
167
168
173
200
208
209
227
228
273
333
364
365
366
367
368
369
370
371
372
373
374
375
378
379
381
382
383
388
391
392
398
399
400
401
402
403
404
405
444
445
446
447
448
449
457
458
481
482
545
554
559
560
567
568
569
571
607
632
640
680
681
684
685
686
687
694
695
706
707
716
717
718
719
720
722
723
725
726
728
729
730
743
744
745
746
754
775
858
864
865
867
868
869
870
871
888
907
908
909
953
956
957
958
959
960
965
966
980
981
982
991
992
993
994
995
1020
1021
1022
1023
1024
1025
1026
1027
1033
1034
1035
1054
1055
1056
1057
1058
1059
1066
1068
1122
1123
1141
1149
1200
1201
1202
1203
1204
1206
1208
1221
1232
1233
1234
1235
1236
1248
1249
1250
1251
1252
1276
1277
1278
1280
1281
1282
1283
1284
1285
1286
1288
1289
1358
1359
1360
1367
1368
1369
1370
1371
1372
1388
1392
1393
1439
1459
1460
1476
1499
1500
1501
1514
1515
1516
1521
1522
1525
1533
1534
1590
1593
1594
1639
1640
1681
1682
1683
1684
1685
1686
1687
1688
1689
1694
1695
1696
1702
1717
1727
1728
1731
1732
1734
1735
1752
1753
1754
1755
1757
1772
1773
1774
1775
1797
1798
1799
1809
1810
1811
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1852
1853
1854
1855
1863
1866
1867
1871
1872
1882
1883
1886
1888
1892
1893
1900
1901
1916
1918
2049
2071
2072
2073
2074
2075
2085
2122
2131
2132
2133
2139
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2159
2160
2178
2225
2226
2230
2249
2250
2253
2254
2295
2298
2299
2300
2301
2302
2303
2335
2336
2337
2338
2342
2368
2377
2395
2406
2414
2423
2425
2428
2459
2488
2489
2490
2509
2510
2513
2516
2517
2521
2522
2524
2525
2526
2529
2532
2533
2534
2535
2566
2573
2640
2643
2667
2672
2673
2674
2675
2676
2677
2730
2733
2734
2735
2736
2775
2777
2783
2788
2789
2790
2791
2796
2797
2811
2812
2817
2832
2833
2877
2913
2914
2915
2916
2917
2918
2919
2920
2921
2928
2930
2931
2932
2934
2935
2936
2937
2938
2957
3008
3055
3056
3071
3072
3095
3114
3115
3116
3117
3121
3122
3158
3168
3173
3181
3182
3260
3261
3266
3274
3276
3321
3322
3328
3329
3441
3442
3443
3445
3446
3447
3448
3449
3450
3451
3453
3456
3457
3463
3526
3539
3544
3551
3560
3562
3566
3570
3575
3582
3583
3584
3588
3596
3598
3599
3605
3607
3608
3619
3630
3637
3638
3640
3662
3668
3677
3686
3687
3691
3692
3694
3700
3710
3718
3719
3724
3731
3739
3751
3758
3788
3789
3791
3803
3833
3834
3837
3845
3877
3878
3881
3883
3888
3889
3894
3896
3897
3912
3921
3923
3931
3959
3973
3975
3985
4014
4020
4026
4029
4038
4081
4083
4085
4086
4089
4095
4096
4097
4098
4099
4101
4102
4106
4108
4117
4133
4135
4136
4137
4140
4143
4144
4151
4153
4155
4156
4158
4160
4162
4163
4165
4166
4168
4171
4172
4175
4178
4179
4180
4186
4188
4189
4192
4198
4199
4200
4202
4204
4205
4206
4210
4212
4213
4216
4218
4220
4222
4223
4224
4229
4230
4231
4234
4235
4238
4244
4246
4247
4248
4249
4250
4251
4253
4254
4255
4256
4259
4260
4261
4262
4264
4265
4266
4267
4269
4271
4275
4276
4306
4319
4351
4376
4413
4421
4448
4468
4483
4493
4496
4509
4516
4530
4540
4545
4557
4563
4575
4582
4589
4606
4633
4643

In [53]:
places[places["Cluster"]=="[]"]

Empty DataFrame
Columns: [이름, 평점, 주소, 좌표, 구, 위도, 경도, Cluster]
Index: []

In [54]:
places.to_csv("/content/drive/MyDrive/에이콘/0117 등원작업물/data/맛집 리스트 및 소속 cluster.csv", sep=",", index=False)
places.to_excel("/content/drive/MyDrive/에이콘/0117 등원작업물/data/맛집 리스트 및 소속 cluster.xlsx",index=False)

In [31]:
a.index(min(a))

10

In [62]:
places.nsmallest(3, "위도", keep="all").index[0]

4261

In [55]:
places

            이름   평점  ...          경도 Cluster
0         청우참치  4.5  ...  127.019356     [0]
1           정돈  4.3  ...  127.026945     [0]
2        꼼다비뛰드  4.5  ...  127.029487     [0]
3          노들강  4.4  ...  127.025818     [0]
4       영동소금구이  4.4  ...  127.023474     [0]
...        ...  ...  ...         ...     ...
4649  막회무침나라횟집    -  ...  126.899372    [24]
4650    포차인닭갈비    -  ...  126.882620    [17]
4651      명화곱창    -  ...  126.883299    [17]
4652    혜화동돈까스    -  ...  126.898883    [24]
4653      에그스탑    -  ...  126.880570    [17]

[4654 rows x 8 columns]

In [4]:
places = pd.read_csv("data/맛집 리스트 및 소속 cluster.csv")
places

,이름,평점,주소,좌표,구,위도,경도,Cluster
0,청우참치,4.5,서울특별시 강남구 강남대로 632,"(37.5182046, 127.019356)",강남구,37.518205,127.019356,[0]
1,정돈,4.3,서울특별시 강남구 강남대로110길 26 1F,"(37.5035911, 127.0269451)",강남구,37.503591,127.026945,[0]
2,꼼다비뛰드,4.5,서울특별시 강남구 강남대로110길 62,"(37.5033264, 127.0294865)",강남구,37.503326,127.029487,[0]
3,노들강,4.4,서울특별시 강남구 강남대로114길 19,"(37.5061534, 127.0258181)",강남구,37.506153,127.025818,[0]
4,영동소금구이,4.4,서울특별시 강남구 강남대로124길 10 1F,"(37.5088173, 127.0234738)",강남구,37.508817,127.023474,[0]
...,...,...,...,...,...,...,...,...
4649,막회무침나라횟집,-,서울특별시 금천구 시흥대로71길 40,"(37.45521069999999, 126.8993725)",금천구,37.455211,126.899372,[24]
4650,포차인닭갈비,-,서울특별시 금천구 가산디지털1로 168 우림라이온스밸리 A동 지하,"(37.4800992, 126.8826202)",금천구,37.480099,126.882620,[17]
4651,명화곱창,-,서울특별시 금천구 벚꽃로38길 5,"(37.4818785, 126.8832991)",금천구,37.481879,126.883299,[17]
4652,혜화동돈까스,-,서울특별시 금천구 금하로5길 4 1F,"(37.4543357, 126.8988835)",금천구,37.454336,126.898883,[24]
4653,에그스탑,-,서울특별시 금천구 가산디지털1로 171 SK V1빌딩 1F,"(37.4806318, 126.8805702)",금천구,37.480632,126.880570,[17]

In [16]:
scores = pd.read_csv("data/average_scores2.csv")
scores.columns=["이름", "점수"]
scores

          이름    점수
0       청우참치  3.47
1         정돈  3.58
2      꼼다비뛰드  3.80
3        노들강  3.00
4     영동소금구이  3.53
...      ...   ...
4503      소마  3.00
4504    동병상련  4.00
4505     카페잇  2.33
4506    숙수도가  4.67
4507  프로젝트얼스  3.27

[4508 rows x 2 columns]

In [17]:
places_scores = pd.merge(places, scores, on="이름", how="inner")
places_scores

,이름,평점,주소,좌표,구,위도,경도,Cluster,점수
0,청우참치,4.5,서울특별시 강남구 강남대로 632,"(37.5182046, 127.019356)",강남구,37.518205,127.019356,[0],3.47
1,정돈,4.3,서울특별시 강남구 강남대로110길 26 1F,"(37.5035911, 127.0269451)",강남구,37.503591,127.026945,[0],3.58
2,꼼다비뛰드,4.5,서울특별시 강남구 강남대로110길 62,"(37.5033264, 127.0294865)",강남구,37.503326,127.029487,[0],3.80
3,노들강,4.4,서울특별시 강남구 강남대로114길 19,"(37.5061534, 127.0258181)",강남구,37.506153,127.025818,[0],3.00
4,영동소금구이,4.4,서울특별시 강남구 강남대로124길 10 1F,"(37.5088173, 127.0234738)",강남구,37.508817,127.023474,[0],3.53
...,...,...,...,...,...,...,...,...,...
4571,막회무침나라횟집,-,서울특별시 금천구 시흥대로71길 40,"(37.45521069999999, 126.8993725)",금천구,37.455211,126.899372,[24],3.00
4572,포차인닭갈비,-,서울특별시 금천구 가산디지털1로 168 우림라이온스밸리 A동 지하,"(37.4800992, 126.8826202)",금천구,37.480099,126.882620,[17],2.67
4573,명화곱창,-,서울특별시 금천구 벚꽃로38길 5,"(37.4818785, 126.8832991)",금천구,37.481879,126.883299,[17],2.67
4574,혜화동돈까스,-,서울특별시 금천구 금하로5길 4 1F,"(37.4543357, 126.8988835)",금천구,37.454336,126.898883,[24],4.00
4575,에그스탑,-,서울특별시 금천구 가산디지털1로 171 SK V1빌딩 1F,"(37.4806318, 126.8805702)",금천구,37.480632,126.880570,[17],2.00

In [18]:
places_scores.to_csv("data/점수포함 맛집리스트2.csv", sep=",", index=0)